image: php:7.1.3

clone:
    depth: full

pipelines:
  default:
    - step:
        caches:
          - composer
        name: Deploy to Heroku
        deployment: test
        script:
          - php -v
          - apt-get update
          - apt-get install -y unzip git
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
          #- export DB_CONNECTION=pgsql
          - php artisan migrate